### PR TITLE
Add support for iojs's `fs.access` method.

### PR DESCRIPTION
**Pull request by JiangJie**

### CODE REVIEW

**Comment by jonathanong** [comment]
was gonna somehow polyfill this for nodejs but this shall do for now

**Comment by targos** [comment]
The property check is redundant. It is already done by [thenify-all](https://github.com/thenables/thenify-all/blob/master/index.js#L55)

**Comment by targos** [comment]
Could you please land this ?  
I'd like to use fs.access in my koa app

**Comment by jonathanong** [comment]
oops sorry. published!

**Pull request closed without merging**
