### PR TITLE
callback support

### PR DESCRIPTION
**Pull request by dead-horse**

### CODE REVIEW

**Comment by jonathanong** [comment]
this is for https://github.com/normalize/mz/issues/12 right? added on npm

**Comment by dead-horse** [comment]
yep, now people can always use `mz` for both promise and callback.

**Comment by dead-horse** [comment]
should we merge this and release 2.0.0 first? `fs-access` still not complete.

**Comment by jonathanong** [comment]
missed this. merging

**Comment by jonathanong** [comment]
also added you on npm!

**Pull request closed without merging**
