### PR TITLE
Added fdatasync to fs api

### LINKED ISSUE #45: `fs.fdatasync` isn't modernized
Is there a reason for this omission? Otherwise I think it should be promisified just the same.

### PR DESCRIPTION
**Pull request by axit-rasmus**
fixes #45

### CODE REVIEW

**Comment by LinusU** [comment]
> fs.js 100644 → 100755

You, probably accidentally, changed the file to be executable, could you please revert that change? Thanks

**Comment by axit-rasmus** [comment]
Good catch, didn't notice. Fixed

**Comment by LinusU** [comment]
If anyone can make a release, please feel free to merge and release, otherwise I will fix it when I'm not at work 👌

**Comment by dead-horse** [comment]
LGTM

**Comment by dead-horse** [comment]
2.6.0

**Comment by LinusU** [comment]
Thank you!

**Pull request merged**
